name: Generate briefs indexes

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *' # daily at 03:00 UTC (adjust as needed)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run index generator
        run: |
          chmod +x ./scripts/generate_indexes.js || true
          node ./scripts/generate_indexes.js

      - name: Commit any generated index files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add briefs/**/index.md || true
          if ! git diff --staged --quiet; then
            git commit -m "chore: auto-generate briefs course indexes" || true
            git push
          else
            echo "No changes to commit"
          fi